FEATURES_LIST = (
    ('air_conditioning', 'Air Conditioning'),
    ('balcony', 'Balcony'),
    ('dishwasher', 'Dishwasher'),
    ('fireplace', 'Fireplace'),
    ('furnished', 'Furnished'),
    ('garage_parking', 'Garage Parking'),
    ('hardwood_floor', 'Hardwood Floor'),
    ('laundry', 'Laundry'),
    ('parking', 'Parking'),
    ('pool', 'Pool'),
    ('storage', 'Storage'),
    ('wheelchair', 'Wheelchair'),
    ('yard', 'Yard'),
    ('elevator', 'Elevator'),
    ('gym', 'Gym'),
    ('security', 'Security'),
    ('doorman', 'Doorman'),
    ('newly_renovated', 'Newly Renovated'),
    ('pets_allowed', 'Pets Allowed'),
    ('smoking_allowed', 'Smoking Allowed'),
    ('utilities_included', 'Utilities Included'),
    ('waterfront', 'Waterfront'),
    ('sea_view', 'Sea View'),
    ('mountain_view', 'Mountain View'),
    ('city_view', 'City View'),
    ('insulation', 'Insulation'),
    ('internet', 'Internet'),
    ('cable_tv', 'Cable TV'),
    ('gas', 'Gas'),
)
