version: "3.8"
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - ./.env
  
  redis:
    image: redis:6.0.9-alpine
    ports:
      - "6379:6379"
  api:
    image: turianpy/housing_api:latest
    restart: always
    volumes:
      - housing_api_static:/app/static
      - housing_api_media:/app/media
      - ../housing_api:/app
    depends_on:
      - db
      - redis
    env_file:
      - ./.env
  celery:
    image: turianpy/housing_api:latest
    container_name: celery
    command:
      - /bin/sh
      - -c
      - |
        cd housing_api
        celery -A housing_api worker -l INFO
        celery -A housing_api beat -l INFO
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    env_file:
      - ./.env
    depends_on:
      - db
      - api
      - redis
  proxy:
    image: nginx:1.19.6-alpine
    ports:
      - "80:80"
    volumes:
      - housing_api_static:/var/html/housing_api_static/
      - housing_api_media:/var/html/housing_api_media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
volumes:
  db:
  housing_api_static:
  housing_api_media: