version: "3.8"
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - ./.env
  api:
    image: turianpy/housing_api:latest
    restart: always
    volumes:
      - housing_api_static:/app/static
      - housing_api_media:/app/media
      - ../housing_api:/app
    depends_on:
      - db
    env_file:
      - ./.env
  proxy:
    image: nginx:1.19.6-alpine
    ports:
      - "80:80"
    volumes:
      - housing_api_static:/var/html/housing_api_static/
      - housing_api_media:/var/html/housing_api_media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
volumes:
  db:
  housing_api_static:
  housing_api_media: