# Generated by Django 4.2.3 on 2023-07-25 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_remove_rentdetails_for_rent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='for_rent',
        ),
    ]
