# Generated by Django 4.2.3 on 2023-07-25 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_rentdetails_deposit_amount_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='longitude',
        ),
    ]
