# Generated by Django 4.2.3 on 2023-07-26 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_remove_location_latitude_remove_location_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='main',
        ),
    ]
