# Generated by Django 4.2.3 on 2023-07-26 13:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0010_remove_image_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('address', 'city', 'state', 'zipcode', 'country')},
        ),
        migrations.AlterUniqueTogether(
            name='property',
            unique_together={('title', 'owner')},
        ),
    ]
