# Generated by Django 4.2.3 on 2023-07-26 13:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0011_alter_property_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='agent',
        ),
        migrations.AddField(
            model_name='property',
            name='agents',
            field=models.ManyToManyField(blank=True, related_name='properties_as_agent', to=settings.AUTH_USER_MODEL),
        ),
    ]
