# Generated by Django 4.2.3 on 2023-07-23 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_confcode_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfCode',
        ),
    ]
