# Generated by Django 4.2.3 on 2023-07-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_listed'),
        ('users', '0005_delete_confcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='properties.property'),
        ),
    ]
